name: l3bi-r-2026-new
# from l3bi-r-2026
# mars 2026
# test pour ne pas limiter les versions

# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
# defaults changé en nodefaults pour construire l'env sur Mydocker de Saclay, janvier 2025
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # Jupyter dependencies
  - jupyterhub>=4.1.6,<5
  - jupyterlab>=4.4,<5
  - notebook
  - jupyter-resource-usage
  - jupyterlab-topbar-text
  - nodejs
 
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  - jupyterlab-variableinspector
    # https://github.com/lckr/jupyterlab-variableInspector
  - nbresuse
  - libgomp
  
  # R environment (version for Ubuntu 24.04)
  - r-irkernel
  - r-base
  - r-tidyverse
  - r-essentials
  - r-repr

  # Build tools required for Ubuntu 24.04
  - gxx_linux-64
  - gcc_linux-64
  - gfortran_linux-64

  # R packages
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-gplots
  - r-ggplot2
  - r-writexl
  - r-readxl
  - r-rcolorbrewer
  - r-igraph
  - r-ggtangle
  - r-enrichplot
  
  # JupyterLab Variable inspector
  - pip
  - pip:
    - watermark
    - matplotlib
  
